// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muhmsgsjhfeazchbonsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11aG1zZ3NqaGZlYXpjaGJvbnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTcyOTIsImV4cCI6MjA2ODE3MzI5Mn0.Vrn9RraRaM1mZWDcXfcYqMfCsdg4CyaGqRENQ6YjSWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});